version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  node:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase
    volumes:
      - .:/usr/src/app           # Mount the current directory inside the container
      - /usr/src/app/node_modules # Prevent overwriting node_modules with local one
    command: npm run dev          # Use Nodemon to start the server

volumes:
  mongo_data:
